### ISSUE TITLE
Arm64 support

### ISSUE THREAD

**Issue by joakimsle** [orbotix/Sphero-iOS-SDK#10]
Hi,

I'm wondering when you plan to add arm64 support to the Sphero SDK? Our app is currently 64-bit compatible, and we would like to keep it that way even after adding Sphero support to it. 

Thanks in advance,
Joakim

**Comment by sodastsai** [comment]
Hi, it's near the day Apple only accepts 64bit app submission (Feb 1), any progress update?

**Comment by torstenrichter** [comment]
Any updates on this? I also need 64bit support now.

**Comment by VVes** [comment]
Check out the Beta branch.  It contains both Ollie and Sphero support.  It's a completely new SDK, so connection handling is completely different so check out the samples.
