### ISSUE TITLE
RUICalibrateButtonGestureHandler causes crash on dismissViewControllerAnimated

### ISSUE THREAD

**Issue by liborh** [orbotix/Sphero-iOS-SDK#13]
Hello,

I stumbled upon this issue while trying to create tutorial for my app where user calibrates sphero and gets to know the environment. The tutorial was presented modally and beneath it was basic sphero controls with calibration as well. When I call dismissViewControllerAnimated the app crashes on the button that gets passed to RUICalibrateButtonGestureHandler.

Sample project with this issue:
https://github.com/liborh/ModalSphero

Do you recommend some workaround/is this known issue for you?

**Comment by zenelk** [comment]
This should be fixed in the latest beta release. Please open another ticket if you continue to see problems.
