### ISSUE TITLE
- [RKConvenienceRobot enableStablilization:] seems break RKRollCommand when set to NO

### ISSUE THREAD

**Issue by sodastsai** [orbotix/Sphero-iOS-SDK#17]
In the **ButtonDrive** sample of the new SDK in ```beta``` branch, 
I set the stabilization state to NO after connected a Sphero. (like following code, in *ButtonDriveViewController.m*)
```objective-c
- (void)handleConnected {
    [_calibrateHandler setRobot:_robot.robot];
    [_robot enableStablilization:NO];
}
```

After setting this up, the Sphreo ball won't move anymore when I clicked the direction buttons in that sample app (or in my app). (it seems all operations related to ```RKRollCommand``` are broken or no response)
i.e. ```-[RKConvenienceRobot driveWithHeading:andVelocity:]``` and ```+[RKRollCommand commandWithHeading:andVelocity:]```

**Comment by VVes** [comment]
Without stabilization on the robot will not drive.  Stabilization is required for movement.

We can add an Exception if movement is requested without Stabilization.
