### ISSUE TITLE
New SDK in beta branch creates hundreds of threads.

### ISSUE THREAD

**Issue by sodastsai** [orbotix/Sphero-iOS-SDK#19]
Even the **HelloWorld** sample project does so. :sob: 
The highest number I've seen is about 1400 threads.

**Comment by profmike** [comment]
HelloWorld on an iPad Air 2 (iOS 8.1.2): CPU usage is 150-200%, and thread count starts < 10, but grows to ~20 in about 3min.

**Comment by iamcgn** [comment]
I just pushed up a beta2 release with a fix for the CPU usage issue.  The live thread count sits at around 10 for the life of the Hello World sample.

iamcgn
