### ISSUE TITLE
Sphero connection while switching apps. (with new Beta SDK)

### ISSUE THREAD

**Issue by sodastsai** [orbotix/Sphero-iOS-SDK#20]
I've tested this with **Hello World** sample, 

though the ```+ [RKRobotDiscoveryAgent startDiscovery]``` did be called when switching back to the app, but sometimes the app could not receive anymore ```RKRobotChangedStateNotification```. Hence the app could not work with the Sphero ball.

**Comment by profmike** [comment]
HelloWorld often doesn't reconnect to Sphero when transitioning from background to foreground.

**Comment by iamcgn** [comment]
Thanks for the feedback!  I just pushed up a new beta2 release that has a fix for this issue.  Let us know if you're still experiencing these issues.

iamcgn
