### ISSUE TITLE
HelloWorld (beta 3) doesn’t work on iPad 2/iOS 8.2.

### ISSUE THREAD

**Issue by sodastsai** [orbotix/Sphero-iOS-SDK#29]
Works on iPad Air 2 and iPad mini 2, but not iPad 2 running iOS 8.2.

**Comment by zenelk** [comment]
Are you connecting to Sphero or Ollie?

**Comment by sodastsai** [comment]
Sphero

**Comment by zenelk** [comment]
I just pushed a commit that fixes this on my end. Please open another ticket if you continue to see issues. Thanks!
