### ISSUE TITLE
kRobotRemoteRSSIChangedNotification is not working.

### ISSUE THREAD

**Issue by citysite102** [orbotix/Sphero-iOS-SDK#43]
Hello, everything works perfect but the kRobotRemoteRSSIChangedNotification seems not working after connecting (or before) to a Ollie device, is there any command need to be sent to Ollie for initialization?

**Comment by citysite102** [comment]
And there is another issue about the connection of multiple sphero under iOS SDK, sometimes the Sphero device will stop sending any robot state notification although the [[RKDiscoveryAgentClassic sharedAgent] isDiscovering] = YES. and we cannot find the Sphero in the available robots of [RKDiscoveryAgentClassic sharedAgent] although we already connect to multiple sphero from the bluetooth setting page.

**Comment by iamcgn** [comment]
@citysite102 Remote RSSI isn't a supported command on Ollie.  I apologize that this hasn't been communicated through the SDK.
