### ISSUE TITLE
Release for SPRK+

### ISSUE THREAD

**Issue by citysite102** [orbotix/Sphero-iOS-SDK#49]
Hello, will the Sphero SPRK+ be included in this iOS-SDK, if so, when will the new version SDK be released? We look forward to programming SPRK+, any further information is appreciated.

**Comment by zenelk** [comment]
I'm going to notify people internally of this question and see if I can't get you an answer. Thanks for being patient :)

**Comment by iamcgn** [comment]
@citysite102 Please check out the current beta branch. That build of the SDK includes SPRK+ support.
