### ISSUE TITLE
Issues with ResponseObservers in Swift 3

### ISSUE THREAD

**Issue by gabriellet** [orbotix/Sphero-iOS-SDK#55]
Hi, is there more guidance on how to correctly implement a response observer for Sphero in Swift? I'm having a difficult time doing this correctly and have already looked at the docs to no avail.

**Comment by iamcgn** [comment]
@gabriellet,
If you're using swift 3 the compiler automatically simplified the addResponseObserver and removeResponseObserver methods to just add(observer: RKResponseObserver!) and remove(observer: RKResponseObserver!). As long as you implement the RKResponseObserver protocol you should just need to call robot.add(self).

**Comment by gabriellet** [comment]
Thank you so much! This works!
