### ISSUE TITLE
Can't build application with Xcode 5/iOS7

### ISSUE THREAD

**Issue by stefankendall** [orbotix/Sphero-iOS-SDK#7]
![screen shot 2013-10-06 at 9 55 50 pm](https://f.cloud.github.com/assets/228889/1278019/b1601dce-2ef3-11e3-89ec-04163023e5d7.png)

When I use the provided template or manually add the framework files, I get the linking errors shown in the attached screenshot. 

This is a pretty immediate blocker for anyone looking to make iOS7 apps.

**Comment by ArchitRai** [comment]
What about arm64 ?
please update

**Comment by sodastsai** [comment]
arm64 support is in the [beta branch](https://github.com/orbotix/Sphero-iOS-SDK/tree/Beta)

**Comment by ArchitRai** [comment]
thanks i am trying it. :-)

**Comment by ArchitRai** [comment]
this beta Branch also not working if deployment target is ios7 or ios 8 .
same error
  "std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()", referenced from:
      __GLOBAL__I_a in RobotKit(RKAchievementManager.o)
  "std::string::reserve(unsigned long)", referenced from:
      std::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(char const*, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in RobotKit(RKAchievementManager.o)
  "std::string::_Rep::_S_empty_rep_storage", referenced from:

**Comment by sodastsai** [comment]
http://docs-beta.gosphero.com/getting-started/

Did you link your app with ```libc++```

**Comment by ArchitRai** [comment]
thanks for link, i have link my app with libc++, -lstdc++ ,-lsqlite3 ,-ObjC
